# Railway deployment configuration
# BIST AI Smart Trader v2.0

[build]
builder = "nixpacks"

[deploy]
startCommand = "python simple_api_server.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
