name: 🚀 Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: 📦 Install dependencies
      run: |
        cd backend
        pip install -r requirements.production.txt
        
    - name: 🧪 Run tests
      run: |
        cd backend
        python test_prd_v2_modules.py
        
    - name: 🐳 Build Docker image
      run: |
        cd backend
        docker build -t bist-ai-trader .
        
    - name: 📋 Deploy summary
      run: |
        echo "🚀 PRD v2.0 BIST AI Smart Trader hazır!"
        echo "✅ Tüm modüller test edildi"
        echo "🐳 Docker image build edildi"
        echo "📡 Railway'e manuel deploy için:"
        echo "   railway login"
        echo "   railway init"
        echo "   railway up"
